### PR TITLE
Convert all challenges to the new YAML format

### PR DESCRIPTION
**Pull request by bocharsky-bw**
According to the https://github.com/KnpLabs/KnpUniversity/pull/476

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
@weaverryan Hey, I left some TODO comments in `challenges.yml`... What do you think, can we implement this features in `BehatExpressionProvider`? How do you see the grading system for Behat?

**Comment by weaverryan** [comment]
@bocharsky-bw I thought this one might get a little more complicated :). But actually, I really like what you did with the proposed grading (near the todos). It feels simple to me, and you're checking the right stuff. I think we should do exactly what you're proposing - add this stuff to the BehatExpressionProvider.

The system may need to be tweaked to show the correct _output_, as this system isn't executing PHP files, but that's a separate issue that we need to discuss with @Leannapelham (i.e. what _should_ we show the user?)

**Comment by bocharsky-bw** [comment]
All MC are checked in this PR - they work and display fine!

**Comment by weaverryan** [comment]
@bocharsky-bw the comments you left in this file were _really_ useful  - nice job :)

**Pull request merged**
